#!/bin/sh
second=1
minute=$((second * 60))
hour=$((minute * 60))
day=$((hour * 24))

offset=$(python -c 'import time; print(-time.timezone)')

base=70
delta=20

brightnessctl -q set \
	"$(echo "$base - $delta * c($(((EPOCHSECONDS + offset) % day)) / $day * 2 * 3.14159)" | bc -l)"
