#!/bin/sh

for file in */; do (
	set -e
	[ -e "$file" ] || exec echo 'clean'
	i="$(cat "$file/.m/read")"
	[ "$(date +%s)" -gt "$((i + (60 * 60 * 24 * 7)))" ] && {
		rm -r -- "$file"
		exec echo 'rm' "$(basename "$file")"
	}
); done

exec true
