#!/bin/sh
set -e

o="$PWD"
cd .io
i="$(head -n1 i)"
echo "$i"

# todo: sftp?
rsync -rz --delete -- "$i:maildir/new/" o

set +e

for file in o/*; do (
	[ -e "$file" ] || exec echo 'empty'

	mail="$(basename "$file")"
	o="$o/$mail"

	[ -e "$o" ] || {
		bin/parse "$file" "$o"
		echo 'new' "$mail"
	}

	mv -- "$file" "$o/.m/raw"
	ssh "$i" -- mv -- "maildir/new/$mail" 'maildir/cur/'
); done

exec true
