#!/bin/sh
set -e

o="$PWD"
cd .io
i="$(cat i)"

rsync -rvz --delete -- "$i:maildir/new/" o

for file in o/*; do (
	[ -e "$file" ] || exec echo 'empty'

	mail="$(basename "$file")"
	o="$o/$mail"

	[ -e "$o" ] || {
		ssh "$i" -- mv -- "maildir/new/$mail" 'maildir/cur/'
		bin/parse "$file" "$o"
		mv -- "$file" "$o/src"
		exec echo 'new' "$mail"
	}
) || true; done
