#!/bin/sh
set -eux

epoch=$(date +%s)

second=1
minute=$((second * 60))
hour=$((minute * 60))
day=$((hour * 24))

tz_offset=$(python -c 'import time; print(-time.timezone)')

now=$(((epoch + tz_offset) % day))

i_waketime=$((6 * hour + 30 * minute))
i_sleeptime=$((8 * hour + 30 * minute))

o_bedtime=$((day + i_waketime - i_sleeptime))

o_sleeptime=$(set -- $((now)) $((i_waketime)) $((day)) && [ "$1" -lt "$2" ] && echo $(($2 - $1)) || echo $(($3 - $1 + $2)))

date --date "@$((epoch + i_sleeptime))" +'%w' | grep "[60]" -q && exit

printf_hm() { printf "$1" $(($2 / hour)) $(($2 % hour / minute)); }

[ $((o_sleeptime)) -lt $((i_sleeptime + (1 * hour))) ] && notify-send \
	-t $((1000 * minute / 2)) \
	-- 'bedtime' \
	"@$(printf_hm '%02i/%02i' $((o_bedtime))) -$(printf_hm '%i/%02i' $((o_sleeptime)))" ||
	true
