#!/bin/sh
set -eu

pkill -0 '^swaylock$' && niri msg action power-off-monitors || true

second=1
minute=$((second * 60))
hour=$((minute * 60))
day=$((hour * 24))

tz_offset=$(python -c 'import time; print(-time.timezone)')

cd "$DOTFILES/share/brightness"
set -- "$(cat base)" "$(cat delta)"

f=$(echo "c($((($(date +%s) + tz_offset) % day)) / $day * 2 * 3.14159)" | bc -l)
o="$(echo "$1 - $2 * $f" | bc)"

echo "$1 - $2 * $f = $o"

brightnessctl -q set "$o"
