#!/bin/sh
set -e

cd "$DOTFILES/git"

( set -e
	i="$(git config get user.name)"

	mkdir -p "github.com/$i" && cd "github.com/$i"

	for i in $(curl -s "https://api.github.com/users/$i/repos" | jq '.[].ssh_url'); do (
		set -e
		i="$(echo $i | sed -e 's/.....//' -e 's/.....$//')"
		j="$(basename "$i")"
		[ -d "$j" ] || git clone "$i"
		cd "$j"
		git pull
) done )
