#!/bin/sh
PLATFORM="$(
	command >/dev/null -v pacman && exec echo arch
	command >/dev/null -v termux-reload-settings && exec echo android
	command >/dev/null -v apt && exec echo debian
	exec echo unknown
)"

export accent="$(tput setaf 5)"

[ "$PLATFORM" = 'unknown' ] || . "$DOTFILES/lib/sh/platform/$PLATFORM"

export PLATFORM
