#!/usr/bin/env sh
echo "init"
git submodule update --init --recursive

true && ( echo "packages"
	sudo pacman -Syu

	sudo pacman -S git base-devel networkmanager 
	sudo pacman -S tmux neovim ranger
	sudo pacman -S vlc qbittorrent libreoffice-still gimp firefox feh
	sudo pacman -S nvidia nvidia-utils nvidia-settings lib32-nvidia-utils xorg xorg-apps xorg-server xorg-xinit pipewire dunst picom flameshot 
	sudo pacman -S xdotool xsel xclip bc qt6-tools bluez bluez-utils libxinerama libxft bash-completion

	AUR_HELPER=paru
	sudo pacman -S $AUR_HELPER || ( cd $(mktemp -d) && git clone "https://aur.archlinux.org/$AUR_HELPER" . && makepkg -si )
	$AUR_HELPER -S mkinitcpio-firmware bemoji github-desktop-bin
echo )

true && ( echo "config/" && cd config
	mkdir ~/.config
	sudo mkdir /root/.config

	lncfg() {
		ln -sf "$(pwd)/$1" $2
		echo -e "\t$1"
	}
	slncfg() {
		lncfg $1 "$HOME/$2"
		sudo ln -sf "$HOME/$2" "/root/$2"
	}

	slncfg bash/rc .bashrc
	slncfg bash/profile .bash_profile
	slncfg tmux .tmux.conf
	slncfg nvim .config/nvim

	lncfg xrc ~/.xinitrc
	lncfg neofetch ~/.config/neofetch/config.conf
	lncfg flameshot ~/.config/flameshot/flameshot.ini

	cp git ~/.gitconfig
	sudo cp *.desktop /usr/share/applications
	sudo cp dunst /etc/dunst/dunstrc
	sudo cp grub /etc/default/grub
	sudo cp issue /etc/issue
	sudo cp picom /etc/xdg/picom.conf
	sudo cp pacman /etc/pacman.conf
	sudo cp nobeep /etc/modprobe.d/nobeep.conf
	sudo cp paru /etc/paru.conf
echo )

true && (
( echo "program/" && cd program
	for dir in */; do (
		echo -e "\t${dir}build"
		cd $dir
		. ./build
	) done
echo )
( echo "etc/" && cd etc
	mkdir ~/.secret
	( cd fehfetch && ./build )
	sudo cp dconfirm /usr/bin
	sudo cp smenu /usr/bin
	sudo cp cat.png /boot/grub/bg.png
echo )
)

. ~/.bash_profile
