#!/bin/sh
cd $(dirname $0)

sudo paman -Syu
sudo pacman -S base-devel networkmanager 
sudo pacman -S git tmux neovim bash-completion
sudo pacman -S vlc qbittorrent libreoffice-still gimp firefox feh
sudo pacman -S nvidia nvidia-utils nvidia-settings lib32-nvidia-utils xorg xorg-apps xorg-server xorg-xinit pipewire
sudo pacman -S blender obs-studio xdotool xsel xclip bc flameshot qt6-tools fortune-mod cowsay btop cmatrix bluez bluez-utils lolcat telegram-desktop libxinerama libxft neofetch dunst picom discord python jdk-openjdk steam

(
	cd $(mktemp -d)
	git clone https://aur.archlinux.org/paru.git
	cd paru
	makepkg -si
)

paru --aur -S mkinitcpio-firmware bemoji spotify github-desktop-bin

cd program
cd dwm
sudo make clean install
cd ../slstatus
sudo make clean install
cd ../dwmblocks
sudo make clean install
cd ../dmenu
sudo make clean install
cd ../st
sudo make clean install
cd ../slock
sudo groupadd nogroup
sudo make clean install
cd ../systat
./build
cd ../
cd ..

cd config
ln -sf $(pwd)/bash/rc ~/.bashrc
sudo ln -sf ~/.bashrc /root/.bashrc
ln -sf $(pwd)/bash/profile ~/.bash_profile
sudo ln -sf ~/.bash_profile /root/.bash_profile
ln -sf $(pwd)/bash/logout ~/.bash_logout
sudo ln -sf ~/.bash_logout /root/.bash_logout
ln -sf $(pwd)/tmux ~/.tmux.conf
sudo ln -sf ~/.tmux.conf /root/.tmux.conf
ln -sf $(pwd)/nvim ~/.config/nvim
sudo mkdir /root/.config
sudo ln -sf ~/.config/nvim /root/.config/nvim
ln -sf $(pwd)/xrc ~/.xinitrc
cp neofetch ~/.config/neofetch/config.conf
cp btop ~/.config/btop/btop.conf
cp flameshot ~/.config/flameshot/flameshot.ini
sudo cp dunst /etc/dunst/dunstrc
sudo cp grub /etc/default/grub
sudo cp issue /etc/issue
sudo cp picom /etc/xdg/picom.conf
sudo cp pacman /etc/pacman.conf
sudo cp nobeep /etc/modprobe.d/nobeep.conf
sudo cp nvim/desktop /usr/share/applications/nvim.desktop
sudo cp paru /etc/paru.conf
cd ..

sudo cp etc/cat.png /boot/grub/bg.png

sudo cp script/dconfirm /bin
sudo cp script/smenu /bin
sudo cp script/dspotify /bin

bash
