#!/usr/bin/env sh
git submodule update --init --recursive || exit

cd() { command cd "$@" && echo "cd $*" || exit; }

( cd config
	i() { set "$1" "$i/${2:-"$1"}"
		mkdir -p "$(dirname "$2")"
		ln -sfT "$PWD/$1" "$2" || return
		echo "	ln '$2' < '$1'"; }

	( cd xdg; i="$HOME/.config"
		for f in *; do i "$f"; done )

	( cd home; i="$HOME"
		i bash/profile .bash_profile
		i bash/rc .bashrc
		i ssh .ssh/ssh_config
		i xinitrc .xinitrc
		i inputrc .inputrc )

	i() { set "$1" "$i/$2"
		sudo mkdir -p "$(dirname "$2")"
		sudo cp "$1" "$2" || return
		echo "	sudo cp '$1' > '$2'"; }

	( cd etc; i='/etc'
		i pacman pacman.conf
		i ssh ssh/sshd_config
		i grub default/grub )
echo )

( sudo pacman -Syu
	AUR_HELPER='paru'
	i() { "$AUR_HELPER" -S "$@"; }
	command -v "$AUR_HELPER" || ( cd "$(mktemp -d)"; git clone "https://aur.archlinux.org/$AUR_HELPER" . && makepkg -si )
	i neovim tmux openssh
	i lf btop fastfetch ripgrep reflector ufw
	i jdk-openjdk rust python deno nasm
	i nvidia-open nvidia-utils nvidia-settings xorg xorg-xinit xkb-switch pipewire libnotify ttf-jetbrains-mono ttf-nerd-fonts-symbols-mono noto-fonts-emoji noto-fonts-cjk
	i obs-studio vlc qbittorrent libreoffice-still gimp firefox torbrowser-launcher bemoji dunst picom flameshot feh
echo )

( cd program
	for i in */; do (
		cd "$i"
		./build
	) done
echo )

( cd etc
	sudo localectl set-x11-keymap us
	sudo localectl set-keymap --no-convert us

	sudo systemctl enable reflector.timer

	sudo cp cat.png /boot/grub/bg.png
	sudo grub-mkconfig -o /boot/grub/grub.cfg

	sudo ufw reset
	sudo ufw default deny incoming
	sudo ufw default allow outgoing
	sudo ufw allow ssh
	sudo ufw enable
echo )

exec "$SHELL"
