#!/usr/bin/env sh
git submodule update --init --recursive
set -ex && export SHELLOPTS

( cd config; set +x
	i() { set -- "$PWD/$1" "$i/$2"
		mkdir -p "$(dirname "$2")"
		ln -sfT "$1" "$2"
		echo "'$2' < '$1'"; }

	( cd xdg; i="$HOME/.config"
		for f in *; do i "$f" "$f"; done )

	( cd home; i="$HOME"
		i bash/profile .bash_profile
		i bash/rc .bashrc
		i ssh/config .ssh/config
		i icons/ .local/share/icons/default
		i inputrc .inputrc )

	sudo -v

	i() { set -- "$PWD/$1" "$i/$2"
		sudo mkdir -p "$(dirname "$2")"
		sudo cp -rT "$1" "$2"
		echo "'$1' > '$2'"; }

	( cd etc; i='/etc'
		i locale locale.conf
		i sudoers/ sudoers.d
		i pacman pacman.conf
		i ssh ssh/sshd_config
		i grub default/grub )
echo )

( sudo pacman -Syu
	AUR_HELPER=paru
	i() { $AUR_HELPER -S "$@" || true; }
	command -v $AUR_HELPER || ( cd "$(mktemp -d)"; git clone "https://aur.archlinux.org/$AUR_HELPER" .; makepkg -si )

	i neovim tmux openssh \
		lf btop fastfetch ripgrep reflector ufw ffmpeg
	i niri pipewire nvidia-open \
		mako swww fuzzel alacritty quickshell fcitx5 \
		torbrowser-launcher qbittorrent-nox libreoffice-still gimp obs-studio vlc blender \
		ttf-nerd-fonts-symbols-mono noto-fonts noto-fonts-emoji noto-fonts-cjk
echo )

( cd etc; i() { sudo "$@"; }
	i cp locale/arttal.locale /usr/share/i18n/locales/arttal
	i cp locale/locale.gen /etc/locale.gen
	i locale-gen

	i systemctl enable reflector.timer

	i cp cat.png /boot/grub/bg.png
	i grub-mkconfig -o /boot/grub/grub.cfg

	i ufw reset
	i ufw default deny incoming
	i ufw default allow outgoing
	i ufw allow ssh
	i ufw enable
	i ufw reload
echo )

( cd bin/src
	for i in */; do (
		cd "$i"
		sudo ./build
	) done
echo )

git init
