#!/bin/bash
export DOTFILES="$HOME/dotfiles"

. "$DOTFILES/config/home/sh/profile"

[[ -f ~/.bashrc ]] && . ~/.bashrc

[ "$PLATFORM" = 'arch' ] && while [[ "$(who | grep -cw "^$USER")" = 1 ]]; do
	echo -e "$bold$(tput setaf 6)\n[x] desktop$(tput setaf 3)\n[p]acman -Syu$(tput setaf 1)\n[e]xit$normal\n[c]ancel"
	read -rs -n1 i || break
	case "$i" in
		'x') dbus-run-session niri --session ;;
		'p') sudo pacman -Syu ;;
		'e') exit ;;
		'c') break ;;
		*) mhm ;;
	esac
done

true
