#!/bin/bash
export DOTFILES="$HOME/dotfiles"
export PATH="$HOME/.local/bin":"$DOTFILES/bin":"$PATH"
export LANG='arttal.UTF-8' LANGUAGE='en_US.UTF-8'

export \
	normal="$(tput sgr0)" \
	bold="$(tput bold)" \
	dim="$(tput dim)" \
	reverse="$(tput rev)" \
	italic="$(tput sitm)" \
	highlight="$(tput smso)" \
	underline="$(tput smul)" \
	blink="$(tput blink)" \
	bell="$(tput bel)" \
	accent="$(tput setaf 2)" \
;
eval "$(dircolors)"

export PS0=
export PROMPT_COMMAND=
export PS1='= '
export PS2='| '
export PS3='? '
export PS4="$PS1"
export SUDO_PROMPT="%U$bold$accent@$normal%H %p$bold$accent#$normal"

export \
	HISTSIZE= \
	HISTFILESIZE= \
	HISTFILE="$HOME/.local/share/history.bash" \
	HISTTIMEFORMAT='[%c] ' \
	HISTCONTROL='ignoredups' \
	HISTIGNORE='fg:bg' \
;

export \
	OPENER='open' \
	TERMINAL='terminal' \
	VISUAL='nvim' \
	EDITOR='nvim' \
	PAGER='less -FXR' \
	BROWSER='firefox' \
	FILES='lf' \
;

[[ -f ~/.bashrc ]] && . ~/.bashrc

command -v who && while [[ "$(who | grep -cw "^$USER")" = 1 ]]; do
	echo -e "$bold$(tput setaf 6)\n[x] desktop$(tput setaf 3)\n[p]acman -Syu$(tput setaf 1)\n[e]xit$normal\n[c]ancel"
	read -rs -n1 i || break
	case "$i" in
		'x') dbus-run-session niri --session ;;
		'p') sudo pacman -Syu ;;
		'e') exit ;;
		'c') break ;;
		*) mhm ;;
	esac
done || true
