#!/bin/bash
export DOTFILES="$HOME/dotfiles"
export PATH="$HOME/.local/bin":"$DOTFILES/bin":"$PATH"

export normal="$(tput sgr0)"
export bold="$(tput bold)"
export dim="$(tput dim)"
export reverse="$(tput rev)"
export italic="$(tput sitm)"
export highlight="$(tput smso)"
export underline="$(tput smul)"
export blink="$(tput blink)"
export bell="$(tput bel)"
export accent="$(tput setaf 6)"
eval "$(dircolors)"

export PS0=
export PROMPT_COMMAND=
export PS1='= '
export PS2='| '
export PS3='? '
export PS4="$PS1"
export SUDO_PROMPT="%U$bold$accent@$normal%H %p$bold$accent#$normal"

export HISTSIZE=
export HISTFILESIZE=
export HISTFILE="$HOME/.local/share/history.bash"
export HISTTIMEFORMAT='[%Y|%w.%d/%m|%H:%M:%S] '
export HISTCONTROL='ignoredups'
export HISTIGNORE='fg:bg'

export OPENER='open'
export TERMINAL='terminal'
export VISUAL='nvim'
export EDITOR="$VISUAL"
export PAGER='less -FXR'
export BROWSER='firefox'
export FILES='lf'

[[ -f ~/.bashrc ]] && . ~/.bashrc

while [[ "$(who | grep -cw "^$USER")" = 1 ]]; do
	echo -e "$bold$(tput setaf 6)\n[x] desktop$(tput setaf 3)\n[p]acman -Syu$(tput setaf 1)\n[e]xit$normal\n[c]ancel"
	read -rs -n1 i || break
	case "$i" in
		'x') dbus-run-session niri --session ;;
		'p') sudo pacman -Syu ;;
		'e') exit ;;
		'c') break ;;
		*) mhm ;;
	esac
done
