#!/bin/bash
[[ $- = *i* ]] || return $(true)
set -o vi

caret() { echo -ne "\e[$* q"; }
mklc() { set -- "$DOTFILES/etc/lc/${1:-.}" "${2:-LICENSE}"
	cp -i -P "$1" "$2" ||
		{ ls "$(dirname "$1")"; return $(false); }
	sed -i "$2" \
		-e "0,/{YEAR}/s//$(command date +'%Y')/" \
		-e "0,/{NAME}/s//$(git config get user.name)/" \
		-e "0,/{EMAIL}/s//$(git config get user.email)/"
	head -n 5 "$2"; }
mktl() { mkdir "$1" && cd "$1" || return
	mkdir src lib io io/i io/o
	echo "# $1" > README.md
	echo '/o' > io/.gitignore
	echo -e > io/build '#!/bin/sh\nset -e'
	echo -e > io/run '#!/bin/sh\nset -e\n\ncd io'
	chmod +x io/build io/run
	git init && git add --all && git commit -m '*'; }
minifetch() { echo "$(tty):$SHLVL '$-'" | fastfetch -C ~/.config/fastfetch/mini.jsonc; }
ff() { find . -name "*$**" 2>/dev/null | $PAGER; }
mhm() { fortune | cowsay -n -f "$(cowsay -l | grep / -v | sed 's/ /\n/g' | shuf -n1)" | lolcat; }
sign() { $VISUAL "$1" && echo " - $USER, $(\date)" | tee -a "$1"; }
cd() { command cd "$@" || return
	git rev-parse --is-inside-work-tree >/dev/null 2>&1 \
		&& __git_ps1='g' || unset __git_ps1
}; cd .

alias \
	s='sudo' \
	x="$OPENER" \
	e="$VISUAL" \
	se="s $VISUAL" \
	p="$PAGER" \
	g='git' \
	f='rg --color=always' \
	t="(exec $TERMINAL >/dev/null 2>&1 &)" \
	c='xsel --clipboard --input' \
	v='xsel --clipboard --output' \
	cl='clear' \
	o='curl -fsL' \
	oo='o -O' \
	r='io/run' \
	rr='io/build && r' \
\
	d='cd' \
	dd='mkdir' \
	ddd='d "$(mktemp -d)"' \
	dx='d "$OLDPWD"' \
	dr='d "$(realpath .)"' \
	dz='d ..' \
	dzz='d ../..' \
	dzzz='d ../../..' \
	ls='ls --color=always' \
	l='ls --group-directories-first' \
	la='l -A' \
	ll='l -a -lh -F' \
	lf="$FILES" \
	rp='realpath .' \
	cp='cp -iv' \
	mv='mv -iv' \
	rm='rm -v' \
	mkdir='mkdir -pv' \
	rmdir='rmdir -v' \
\
	fehbg='feh --no-fehbg --bg-scale' \
	cpb='cp -t ~/.local/bin' \
	history="history | $PAGER +G" \
	tree="tree -C | $PAGER" \
	myip='echo "$(curl -s ipinfo.io/ip)"' \
	date='date +"[%w.%d/%m|%H:%M]"' \
	uptime='uptime -p' \
	..='. ~/.bashrc' \
	...='. ~/.bash_profile' \
	....="exec '$SHELL'" \
	diff='diff --color=always' \
	+x='chmod +x' \
	filesize='du -shc ./.* ./* 2>/dev/null' \
	sshs='eval "$(ssh-agent -s)"' \
	shellcheck='shellcheck -s sh --color' \
;

PS1="$(
	b="\[$bold\]"
	r="\[$normal\]"
	c="\[$accent\]"
	i() { PS1="$*"; }; i

	i "$b$c\w$r"
	i "\$([ \"\$(pwd)\" = \"\$(realpath .)\" ] || echo 'r$c:$r')$PS1"
	i "\${__git_ps1+\$__git_ps1$c:$r}$PS1"
	i "\h $PS1$c"
	[[ "$(id -u)" = 0 ]] && i "$PS1#" || i "\u$b$c@$r$PS1="
	[[ -n "$SSH_CONNECTION" ]] && i "ssh$c:$r$PS1"
	i "$c\$([ \$? = 0 ] && echo + || echo -)$r $PS1"
echo "$r$PS1$r")"

minifetch

[[ -f ~/.config/bashrc ]] && . ~/.config/bashrc
