#!/bin/sh
export DOTFILES="$HOME/dotfiles"

export PATH="$HOME/.local/bin":"$DOTFILES/bin":"$PATH"
export LANG='custom.UTF-8' LANGUAGE='C'
export XDG_CONFIG_HOME="$HOME/.config"

. "$DOTFILES/lib/sh/platform"

eval "$(dircolors)"

normal="$(tput sgr0)"
bold="$(tput bold)"

export PS0=''
export PROMPT_COMMAND=''
export PS1='= '
export PS2='| '
export PS3='? '
export PS4="$PS1"
export SUDO_PROMPT="%U$bold$accent@$normal%H %p$bold$accent#$normal"

export \
	HISTSIZE='' \
	HISTFILESIZE=$((32768 * 2)) \
	HISTFILE="$HOME/.local/share/history.sh" \
	HISTTIMEFORMAT='%c ' \
	HISTCONTROL='ignoredups' \
	HISTIGNORE='fg:bg' \
	;

export \
	OPENER='open' \
	TERMINAL='terminal' \
	VISUAL='nvim' \
	EDITOR='nvim' \
	PAGER='less -FXR' \
	BROWSER='firefox' \
	FILES='lf' \
	;
