#!/bin/sh
set -e

[ -e "$1" ] || {
	tput rev
	exec echo 'no such file'
}

tput setaf 2
file -bL "$1" | fold -s -w "$2"
tput setaf 15
echo

case "$(file -bL --mime-type "$1")" in
'image'/*) jp2a --width="$2" --colors "$1" ;;
*) false ;;
esac && exit

[ -f "$1" ] && grep -Iq . "$1" && exec cat "$1"

tput rev
[ -s "$1" ] || exec echo 'empty'
[ -r "$1" ] || exec echo 'permission denied'
echo 'binary'
