#!/bin/sh
set -e

[ -e "$1" ] || {
	tput rev
	exec echo 'no such file'
}

tput setaf 2
file -bL "$1" | fold -s -w "$2"
tput sgr0 | sed 's/(B//'
echo

[ -d "$1" ] && {
	[ -r "$1" ] || {
		tput rev
		exec echo 'permission denied'
	}
	[ "$(find -L "$1" -maxdepth 1 | wc -l)" = 1 ] && {
		tput rev
		exec echo 'empty'
	}

	cd "$1"
	tree . -L 2 -F -C --noreport --dirsfirst --compress -2 |
		tail -n +2 | sed 's/..//'
	exit
}

case "$(file -bL --mime-type "$1")" in
'image'/*) jp2a --width="$2" --colors "$1" ;;
*) false ;;
esac && exit

[ -f "$1" ] && grep -Iq . "$1" && exec cat "$1"

tput rev
[ -s "$1" ] || exec echo 'empty'
[ -r "$1" ] || exec echo 'permission denied'
echo 'binary'
