#!/bin/sh
xrandr

sysresources=/etc/X11/xinit/.Xresources
[ -f $sysresources ] && xrdb -merge $sysresources
sysmodmap=/etc/X11/xinit/.Xmodmap
[ -f $sysmodmap ] && xmodmap $sysmodmap

userresources=~/.config/x/resources
[ -f "$userresources" ] && xrdb -merge "$userresources"
usermodmap=~/.config/x/modmap
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

for i in /etc/X11/xinit/xinitrc.d/*; do
	[ -x "$i" ] && . "$i"
done; unset i

xset r rate 200 25
xset m 0 0
xbacklight -set 75 -time 0 -steps 1

( cd "$DOTFILES/etc"
	~/.fehbg &
	./discordrpc &
	systat &
	picom &
	dunst &
	flameshot &
) &

~/.config/xinitrc

exec dwm
