#!/bin/sh
xrandr

sysresources=/etc/X11/xinit/.Xresources
[ -f $sysresources ] && xrdb -merge $sysresources
sysmodmap=/etc/X11/xinit/.Xmodmap
[ -f $sysmodmap ] && xmodmap $sysmodmap

userresources="$HOME/.config/x/resources"
[ -f "$userresources" ] && xrdb -merge "$userresources"
usermodmap="$HOME/.config/x/modmap"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

for i in /etc/X11/xinit/xinitrc.d/*; do
	[ -x "$i" ] && . "$i"
done; unset i

xset r rate 200 25
xset m 0 0
xbacklight -set 75 -time 0 -steps 1
~/.fehbg

( cd "$DOTFILES/etc"
	( dir="$(systemd-path user-shared)/python/pypresence"
		cd "$dir" && . bin/activate || {
			python -m venv "$dir"
			cd "$dir" && . bin/activate
			python -m pip install pypresence
		} && python "$OLDPWD/rpc.py" ) &
	systat &
	picom &
	dunst &
	flameshot &
) &

~/.config/xinitrc

exec dwm
