#!/bin/sh
xrandr

xrdb -merge '/etc/X11/xinit/.Xresources'
xmodmap '/etc/X11/xinit/.Xmodmap'
xrdb -merge "$HOME/.config/x/resources"
xmodmap "$HOME/.config/x/modmap"
for i in /etc/X11/xinit/xinitrc.d/*; do . "$i"; done

xset r rate 200 25
xset m 0 0

( cd "$DOTFILES/etc"
	~/.fehbg &
	systat &
	picom &
	dunst &
	flameshot &
) &

~/.config/xinitrc

exec dwm
