#!/bin/sh
xrandr

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
for i in /etc/X11/xinit/xinitrc.d/*; do
	[ -x "$i" ] && . "$i"
done; unset i

( cd "$DOTFILES/etc"
	dir="$(systemd-path temporary-large)"
	~/.fehbg || ( cd fehfetch
		dir="$dir/fehbg/$USER"
		mkdir -p "$dir"
		fastfetch --pipe -s : \
			| sed 's/\x1b.*//' \
			| ./run -d "$dir" -f '/usr/share/fonts/TTF/art.ttf'
		feh --bg-scale "$dir"
	) &
	( dir="$dir/python/pypresence"
		cd "$dir" && . bin/activate || {
			python -m venv "$dir"
			cd "$dir"
			. bin/activate
			python -m pip install pypresence
		}; python "$OLDPWD/rpc.py"
	) &
	systat &
	picom &
	dunst &
	flameshot &
	xbacklight -set 75 -time 0 -steps 1 &
	xset r rate 200 25 &
	xset m 0 0 &
) &

exec dwm
