#!/bin/sh
xrandr

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -d /etc/X11/xinit/xinitrc.d ] && {
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
}

( cd "$DOTFILES/etc"; dir="$(systemd-path temporary-large)"
	~/.fehbg || ( cd fehfetch; dir="$dir/fehbg/$USER"
		rm -rf "$dir"; mkdir -p "$dir"
		fastfetch --pipe -s ":" | sed "s/\x1b.*//g" \
			| ./run -f "/usr/share/fonts/TTF/art.ttf" -d "$dir"
		feh --bg-scale "$dir"
	) &
	( dir="$dir/pypresence"
		[ -d "$dir" ] || {
			python -m venv "$dir"
			. "$dir/bin/activate"
			python -m pip install pypresence
			deactivate
		}
		. "$dir/bin/activate"
		python rpc.py
	) &
	systat &
	picom &
	dunst &
	flameshot &
) &

xbacklight -set 75 -time 0 -steps 1
xset r rate 200 25 
xset m 0 0
exec dwm
