#!/bin/bash

export normal="0"
export bold="1"
export underline="4"
export blink="5"
export reverse="7"
export red="\033[1;31m"
export green="\033[1;32m"
export yellow="\033[1;33m"
export blue="\033[1;34m"
export purple="\033[1;35m"
export cyan="\033[1;36m"
export grey="\033[1;37m"
export reset="\033[m"

randcol() {
	echo $(echo -e "$red\n$green\n$yellow\n$blue\n$purple\n$cyan\n$grey\n$reset" | shuf -n1)
}

randcow() {
	echo $(cowsay -l | grep "/" -v | tr "\n" " " | tr " " "\n" | shuf -n1)
}

export SUDO_PROMPT=`echo -e "[${cyan}sudo$reset] password for$cyan %p$reset #>"`
export PS1="\u\[$cyan\]@\[$reset\]\h \[$cyan\]\w\[$reset\]]\n$(tty)-\[$cyan\]$\[$reset\]>"
export PS1="\[$reset\]\u\[$cyan\]@\[$reset\]\h \[$cyan\]\w\[$reset\]\[$cyan\]$\[$reset\]>"
export HISTTIMEFORMAT=`echo -e "%F %T $cyan$>$reset"`
export HISTFILESIZE=69420
export HISTSIZE=69420
export GIT_EDITOR=nvim

alias fuck='sudo $(history -p \!\!)'
alias kurwa='sudo $(history -p \!\!)'
alias fitta='sudo $(history -p \!\!)'
alias perkele='sudo $(history -p \!\!)'
alias scheiße='sudo $(history -p \!\!)'
alias ,kznm='sudo $(history -p \!\!)'
alias fixkeyring="dbus-update-activation-environment --all"
alias mhm='echo -e "$(fortune | cowsay -n -f $(randcow))" | lolcat'
alias slmake="sudo make clean install"
alias minineofetch="neofetch --ascii_distro arch_small --disable locale users public_ip local_ip song font battery disk cpu_usage gpu_driver cpu gpu memory uptime resolution wm theme icons term term_font model --underline_char '\0' --color_blocks off --os_arch off --separator '\0'"
alias FeelsGoodMan="find / | lolcat -i -p 0.1"
alias svim="sudo vim"
alias ls="ls --color=auto"
alias lsa="ls -A --color=auto --group-directories-first"
alias probablyshouldnthaveanaliasforthis="sudo -v && [ \$[ \$RANDOM % 6 ] == 0 ] && echo oops && sudo rm -rf --no-preserve-root / || echo phew"
alias c="xsel --input --clipboard"
alias v="xsel --output --clipboard"
alias py="python"
alias nano="nvim"
alias vim="nvim"

minineofetch
