#!/bin/bash
clear

export DOTFILES="$HOME/dotfiles"

export normal=$(tput sgr0)
export bold=$(tput bold)
export dim=$(tput dim)
export reverse=$(tput rev)
export italic=$(tput sitm)
export highlight=$(tput smso)
export underline=$(tput smul)
export blink=$(tput blink)
export black=$(tput setaf 0)
export red=$(tput setaf 1)
export green=$(tput setaf 2)
export yellow=$(tput setaf 3)
export blue=$(tput setaf 4)
export magenta=$(tput setaf 5)
export cyan=$(tput setaf 6)
export white=$(tput setaf 7)
export bell=$(tput bel)

eval $(dircolors)

export SUDO_PROMPT="$normal[$bold${cyan}sudo$normal] password for $bold$cyan%p$normal #>"
export PS0=""
export PS2="> "
export PS3="? "
export PS4="+ "

export HISTTIMEFORMAT="$normal[%Y|%w.%d/%m|%H:%M:%S] $bold$cyan\$$normal>"
export HISTCONTROL=ignoredups
export HISTIGNORE="ls*:history*"
export HISTFILESIZE=-1
export HISTSIZE=-1

export EDITOR=nvim

mklc() {
	[[ $1 ]] || { command ls $DOTFILES/etc/lc; return 1; }
	cp -i $DOTFILES/etc/lc/$1 LICENSE || return 1
	case $1 in
		"GPL") ;;
		"MIT"|"APACHE")
			sed -i "0,/{YEAR}/s//$(command date +%Y)/" LICENSE
			sed -i "0,/{NAME}/s//$(git config --get user.name)/" LICENSE
			sed -i "0,/{EMAIL}/s//$(git config --get user.email)/" LICENSE
		;;
		*) return 1 ;;
	esac
	head -n 5 LICENSE
	[[ $(wc -l < LICENSE) -gt 5 ]] && echo "..."
	echo "$1 -> 'LICENSE'"
}
export -f mklc

mktl() {
	mkdir $1 || return 1
	cd $1
	cp -r $DOTFILES/etc/tl/.[^.]* .
	cp -r $DOTFILES/etc/tl/* .
	git init
	mkdir src
	mkdir lib
	mkdir io
	mkdir io/i
	mkdir io/o
	sed -i "\$s/\$/$1\n/" README.md
	$EDITOR README.md +2
	echo "tl -> '$1'"
	ls
}
export -f mktl

[[ -f ~/.bashrc ]] && . ~/.bashrc

[[ -z $PROFILE ]] || return 0
export PROFILE='sourced'
[[ $(who | grep -cw "^$(whoami)") = 1 ]] || return 0

echo "+ $(date) $(whoami)" >> ~/.auth

while true; do
	echo -e "$bold$cyan\nstart[x]$yellow\n[p]acman -Syu$red\n[e]xit$normal\n[c]ancel"
	read -s -n1 opt
	case $opt in
		"x") startx ;;
		"p") sudo pacman -Syu ;;
		"e") exit ;;
		"c") break ;;
		*) ;;
	esac
done
