#!/bin/bash
[[ -f ~/.bashrc ]] && . ~/.bashrc

neofetch
pacman -V
lsblk
ls -la /

while true; do
	echo -e "$bold$cyan\nstart[x]$yellow\n[u]pdate$normal\n[c]ancel\n"
	read -s -n1 opt
	case $opt in
		"u") paru || sudo pacman -Syu ;;
		"x") startx; break ;;
		"c") break ;;
		*) ;;
	esac
done
