#!/bin/bash
export DOTFILES="$HOME/dotfiles"

export normal=$(tput sgr0)
export bold=$(tput bold)
export dim=$(tput dim)
export reverse=$(tput rev)
export italic=$(tput sitm)
export highlight=$(tput smso)
export underline=$(tput smul)
export blink=$(tput blink)
export black=$(tput setaf 0)
export red=$(tput setaf 1)
export green=$(tput setaf 2)
export yellow=$(tput setaf 3)
export blue=$(tput setaf 4)
export magenta=$(tput setaf 5)
export cyan=$(tput setaf 6)
export white=$(tput setaf 7)
export accent="$cyan"
export bell=$(tput bel)
eval "$(dircolors)"

export PS0=
export PROMPT_COMMAND=
export PS1='= '
export PS2='| '
export PS3='? '
export PS4="$PS1"

export SUDO_PROMPT="$normal%p$bold$accent#$normal"

export HISTTIMEFORMAT='[%Y|%w.%d/%m|%H:%M:%S] '
export HISTCONTROL='ignoredups'
export HISTIGNORE='ls:lsa:history*'
export HISTFILESIZE=
export HISTSIZE=

export TERMINAL='st'
export EDITOR='nvim'
export VISUAL="$EDITOR"
export PAGER='less -FXR'
export BROWSER='firefox'

[[ -f ~/.bashrc ]] && . ~/.bashrc

[[ $(who | grep -cw "^$USER") = 1 ]] || return $(true)

while true; do
	echo -e "$bold$cyan\nstart[x]$yellow\n[p]acman -Syu$red\n[e]xit$normal\n[c]ancel"
	read -rs -n1 opt || break
	case "$opt" in
		'x') startx ;;
		'p') sudo pacman -Syu ;;
		'e') exit ;;
		'c') break ;;
		*) mhm ;;
	esac
done
