#!/bin/sh
set -e
dir="$HOME/music"

venv="$HOME/.local/share/python/yt-dlp"
[ -d "$venv" ] || (
	python -m venv "$venv"
	. "$venv/bin/activate"
	python -m pip install yt-dlp
) && . "$venv/bin/activate"
cd "$(mktemp -d)"
while IFS= read -r line; do
	echo "$line"
	eval "set -- $line"
	file="$dir/$1"
	[ -f "$file" ] && continue
	link="${2:-$(basename "$1")}"
	case "$link" in
		'') continue ;;
		https://*) curl -O "$link" ;;
		*) python -m yt_dlp \
			-x --audio-quality 0 --audio-format best \
			--default-search ytsearch \
			-- "$link" ;;
	esac
	mkdir -p "$(dirname "$file")"
	ffmpeg -i "$(echo ./*)" \
		-f wav "$file" \
		-hide_banner -nostdin
	rm -rf ./*
done
cd ..
rm -rf "$OLDPWD"
