#!/bin/sh
set -e

cd "$1"

i="$HOME/.cache/python/yt-dlp"
[ -d "$i" ] || (
	python -m venv "$i"
	cd "$i"
	. bin/activate
	python -m pip install yt-dlp
); . "$i/bin/activate"

f() { ( set -e; i="$1"
	[ -d "$i" ] && {
		for i in "$i"/*; do f "$i"; done
		exit
	}

	file="$OLDPWD/$i"
	[ -f "$file" ] && {
		echo "$i" | sed 's/../= /'
		exit; }
	source="$(cat "$i")"
	echo "$i" | sed 's/../+ /'

	temp="$(mktemp -d 'music.+.XXX' --tmpdir)"
	( set -e; cd "$temp"
		case "$source" in
			'') exit ;;
			https://*) curl -O "$source" ;;
			*) python -m yt_dlp \
				-x --audio-quality 0 --audio-format best \
				--default-search ytsearch \
				-- "$source" ;;
		esac

		mkdir -p "$(dirname "$file")"
		ffmpeg -i "$(echo ./*)" \
			-f 'mp3' \
			"$file" \
			-hide_banner -nostdin ) || true
	rm -r "$temp"
) || true; }
f .

cd "$OLDPWD"

temp="$(mktemp -d 'music.-.XXX' --tmpdir)"
f() { ( set -e; i="$1"
	[ -e "$i" ] || exit
	[ -d "$i" ] && {
		for i in "$i"/*; do f "$i"; done
		exit; }
	[ -f "$OLDPWD/$i" ] || {
		mkdir -p "$(dirname "$temp/$i")"
		mv "$i" "$temp/$i"
		echo "$i" | sed 's/../- /'; }
) || true; }
f .
rmdir --ignore-fail-on-non-empty "$temp"
