#!/bin/sh
journalctl -u sshd -f -n 1 | while IFS= read -r line; do
	curl "$1" --retry 2 -s -H "Content-Type: application/json" -d \
		"{\"content\": \"$(echo "$line" | sed 's/Accepted publickey for .*/Accepted publickey/')\"}"
	sleep 4
done
