general {
	lock_cmd = .config/niri/bin/lock
}

listener {
	timeout = 100
	on-timeout = systemctl --user stop 'brightness'.timer && brightnessctl set 0
	on-resume = systemctl --user start 'brightness'.timer
}

listener {
	timeout = 190
	on-timeout = .config/niri/bin/bg
}

listener {
	timeout = 200
	on-timeout = niri msg action power-off-monitors
}

listener {
	timeout = 210
	on-timeout = loginctl lock-session
}

listener {
	timeout = 1000
	on-timeout = systemctl suspend
}
