general {
	hide_cursor = true
}

background {
	color = rgba(0, 0, 0, 1.0)
}

label {
	position = 0, 30

	text = cmd[] echo "$USER@$HOSTNAME"
}

input-field {
	position = 0, -30
	size = 360, 60

	outline_thickness = 0

	inner_color = rgba(0, 0, 0, 0.0)
	outer_color = rgba(0, 0, 0, 0.0)
	check_color = rgb(ffffff)
	fail_color = rgb(ff0000)

	font_color = rgb(ffffff)
}
