general {
	hide_cursor = true
}

background {
	color = rgba(0, 0, 0, 1.0)
}

label {
	position = 0, 30

	text = cmd[] echo "$USER@$HOSTNAME"
}

input-field {
	position = 0, -30
	size = 360, 60

	outline_thickness = 0
	rounding = 0

	dots_text_format = *

	font_color = rgb(ffffff)
	inner_color = rgba(0, 0, 0, 0.0)
	check_color = rgba(0, 0, 0, 0.0)
	fail_color = rgb(ff0000)
	swap_font_color = true
}
