general {
	lock_cmd = .config/niri/bin/lock

	before_sleep_cmd = loginctl lock-session
}


listener {
	timeout = 120
	on-timeout = niri msg action power-off-monitors
	on-resume = niri msg action power-on-monitors
}

listener {
	timeout = 300
	on-timeout = loginctl lock-session
}

listener {
	timeout = 600
	on-timeout = systemctl sleep
}
