#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

(
	java -jar $DOTFILES/script/fehfetch.jar --font /usr/share/fonts/TTF/art.ttf --path $(mktemp -d) &
	(
		cd $(mktemp -d)
		python -m venv .venv
		source .venv/bin/activate
		python -m pip install --upgrade pip
		python -m pip install tendo
		python -m pip install pypresence
		python $DOTFILES/script/rpc.py
	) &
	xbacklight -set 75 -time 0 -steps 1 &
	xset m 1/1 1 &
	flameshot &
	dunst &
	systat &
	picom -b &
) &

exec dwm
