#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

( cd $DOTFILES/etc
	( cd fehfetch; dir="$(mktemp -d)"
		fastfetch --pipe -s ":" | sed "s/\x1b.*//g" \
			| ./run -f "/usr/share/fonts/TTF/art.ttf" -d "$dir"
		feh --no-fehbg --bg-scale "$dir"
	) &
	( python -m venv "$(mktemp -d)"
		source "$_/bin/activate"
		python -m pip install pypresence
		python rpc.py
	) &
	systat &
	picom &
	dunst &
	flameshot &
) >/dev/null 2>&1 &


xbacklight -set 75 -time 0 -steps 1
xset r rate 200 25 
xset m 0 0
exec dwm
