#!/bin/sh
set -eu
volume="${1:-1.0}"
target="${2:-default_sink}"

cd "$DOTFILES/share/snd/morse"

mkdir -p o
[ -e 'o/sleep' ] || ffmpeg -f lavfi -i "sine=frequency=0:duration=0.05" -f wav -y -- 'o/sleep'
[ -e 'o/dot' ] || ffmpeg -f lavfi -i "sine=frequency=1000:duration=0.05" -f wav -y -- 'o/dot'
[ -e 'o/dash' ] || ffmpeg -f lavfi -i "sine=frequency=1000:duration=0.15" -f wav -y -- 'o/dash'

i="$(cat | fold -w1)"

play() { pw-play --volume="$volume" --target="$target" -- "$@"; }
_sleep() { play 'o/sleep'; }
dot() { play 'o/dot' && _sleep; }
dash() { play 'o/dash' && _sleep; }

IFS='
'
for c in $i; do
	case "$c" in
	'a')
		dot
		dash
		;;
	'b')
		dash
		dot
		dot
		dot
		;;
	'c')
		dash
		dot
		dash
		dot
		;;
	'd')
		dash
		dot
		dot
		;;
	'e')
		dot
		;;
	'f')
		dot
		dot
		dash
		dot
		;;
	'g')
		dash
		dot
		dot
		;;
	'h')
		dot
		dot
		dot
		dot
		;;
	'i')
		dot
		dot
		;;
	'j')
		dot
		dash
		dash
		dash
		;;
	'k')
		dash
		dot
		dash
		;;
	'l')
		dot
		dash
		dot
		dot
		;;
	'm')
		dash
		dash
		;;
	'n')
		dash
		dot
		;;
	'o')
		dash
		dash
		dash
		;;
	'p')
		dot
		dash
		dash
		dot
		;;
	'q')
		dash
		dash
		dot
		dash
		;;
	'r')
		dot
		dash
		dot
		;;
	's')
		dot
		dot
		dot
		;;
	't')
		dash
		;;
	'u')
		dot
		dot
		dash
		;;
	'v')
		dot
		dot
		dot
		dash
		;;
	'w')
		dot
		dash
		dash
		;;
	'x')
		dash
		dot
		dot
		dash
		;;
	'y')
		dash
		dot
		dash
		dash
		;;
	'z')
		dash
		dash
		dot
		dot
		;;
	'1')
		dot
		dash
		dash
		dash
		dash
		;;
	'2')
		dot
		dot
		dash
		dash
		dash
		;;
	'3')
		dot
		dot
		dot
		dash
		dash
		;;
	'4')
		dot
		dot
		dot
		dot
		dash
		;;
	'5')
		dot
		dot
		dot
		dot
		dot
		;;
	'6')
		dash
		dot
		dot
		dot
		dot
		;;
	'7')
		dash
		dash
		dot
		dot
		dot
		;;
	'8')
		dash
		dash
		dash
		dot
		dot
		;;
	'9')
		dash
		dash
		dash
		dash
		dot
		;;
	'0')
		dash
		dash
		dash
		dash
		dash
		;;
	' ')
		_sleep
		_sleep
		_sleep
		_sleep
		_sleep
		;;
	'.') dot ;;
	'-') dash ;;
	*) false ;;
	esac || tput setaf 1 >&2
	printf '%s' "$c"
	tput sgr0 >&2

	_sleep
	_sleep
done

echo
