#!/bin/sh
set -e
i="$1"
echo "## $*" >> "$i"

i() { sed "$@" -i "$i"; }

[ "$3" = 'HEAD' ] ||
	i "1i# $(cat /dev/urandom |
		tr -d ' ' |
		tr -dc '[:alnum:][:punct:]' |
		head -c 2)"

i "0,/{NAME}/s//$(git config get user.name)/"
i "0,/{EMAIL}/s//$(git config get user.email)/"
