#!/bin/sh

pkg update && pkg upgrade
apt autoremove

rm -vf ~/../usr/etc/profile

pkg install \
	neovim tmux openssh \
	lf ripgrep fastfetch \
	ncurses-utils clang

termux-setup-storage
termux-reload-settings
