#!/bin/sh

( sudo pacman -Syu
	AUR_HELPER=paru
	i() { $AUR_HELPER -S "$@" || true; }
	command -v $AUR_HELPER || ( cd "$(mktemp -d)"; git clone "https://aur.archlinux.org/$AUR_HELPER" .; makepkg -si )

	i neovim openssh tmux \
		lf btop fastfetch ripgrep reflector ufw ffmpeg ly
	i niri pipewire nvidia-open \
		firefox mako swww rofi alacritty quickshell fcitx5 \
		torbrowser-launcher qbittorrent-nox libreoffice-still gimp obs-studio mpv blender kdenlive \
		noto-fonts noto-fonts-emoji noto-fonts-cjk
echo )

( set -ex; cd etc; i() { sudo "$@"; }
	i locale-gen

	i systemctl enable reflector.timer

	i systemctl disable getty@tty1
	i systemctl enable ly@tty1

	i cp -rT ../config/etc/grub/theme /boot/grub/themes/default
	i grub-mkconfig -o /boot/grub/grub.cfg

	i ufw reset
	i ufw default deny incoming
	i ufw default allow outgoing
	i ufw allow ssh
	i ufw enable
	i ufw reload

	gsettings set 'org.gnome.desktop.interface' font-name "$(fc-match sans-serif -f '%{family} %{size}')"
	gsettings set 'org.gnome.desktop.interface' color-scheme 'prefer-dark'
echo )
