#!/bin/sh

( sudo pacman -Syu
	AUR_HELPER=paru
	i() { $AUR_HELPER -S "$@" || true; }
	command -v $AUR_HELPER || ( cd "$(mktemp -d)"; git clone "https://aur.archlinux.org/$AUR_HELPER" .; makepkg -si )

	i neovim lf \
		openssh qbittorrent-nox nginx ufw \
		btop fastfetch ripgrep ly nix tmux ffmpeg
	i niri pipewire nvidia-open \
		mako swww rofi quickshell fcitx5 \
		firefox foot \
		mpv libreoffice-still gimp obs-studio \
		noto-fonts noto-fonts-emoji noto-fonts-cjk
echo )

( set -ex
	systemctl --user enable \
		brightness-fluctuator.timer

	sudo systemctl disable getty@tty1 && sudo systemctl enable ly@tty1

	sudo ufw reset
	sudo ufw default deny incoming
	sudo ufw default allow outgoing
	sudo ufw allow ssh
	sudo ufw enable
	sudo ufw reload

	sudo systemctl enable \
		sshd \
		qbittorrent-nox nginx

	sudo cp -rTL config/etc/grub/theme /boot/grub/themes/default
	sudo grub-mkconfig -o /boot/grub/grub.cfg
echo )
