#!/bin/sh

(
	set +e
	sudo pacman -Syu

	AUR_HELPER=paru
	command -v "$AUR_HELPER" || (
		set -e
		cd "$(mktemp -d)"
		git clone "https://aur.archlinux.org/$AUR_HELPER" .
		makepkg -si
	)

	i() { "$AUR_HELPER" -S "$@"; }

	i neovim lf \
		openssh qbittorrent-nox ufw \
		btop fastfetch ripgrep ly nix tmux ffmpeg
	i niri firefox alacritty \
		mako awww eww rofi \
		fcitx5 easyeffects \
		mpv libreoffice-fresh gimp obs-studio \
		noto-fonts noto-fonts-emoji noto-fonts-cjk

	true
)

(
	set -x

	systemctl --user enable \
		'brightness'.timer

	[ "$(id -u)" = 0 ]

	systemctl disable getty@tty1 && systemctl enable ly@tty1

	ufw reset
	ufw default deny incoming
	ufw default allow outgoing
	ufw allow ssh
	ufw enable

	systemctl enable \
		sshd \
		qbittorrent-nox

	cp -rTL etc/root/grub/theme /boot/grub/themes/default
	grub-mkconfig -o /boot/grub/grub.cfg
)
