#!/bin/sh

[ "$(id -u)" = 0 ] || exit

apt update && apt upgrade

apt install \
	neovim tmux \
	lf ripgrep fastfetch \
	ssh ufw postfix nginx bind9-dnsutils

ufw allow ssh
ufw allow mail
ufw allow http

apt autoremove

echo heartbeat >/sys/class/leds/ACT/trigger
