#!/usr/bin/env sh
export DOTFILES="$PWD"
. 'config/home/bash/platform/unknown'

git submodule update --init --recursive
set -ex && export SHELLOPTS

( cd config; set +x
	i() { set -- "$PWD/$1" "$i/$2"
		mkdir -p "$(dirname "$2")"
		ln -sfT "$1" "$2"
		echo "'$2' < '$1'"; }

	( cd xdg; i="$HOME/.config"
		for f in *; do i "$f" "$f"; done )

	( cd home; i="$HOME"
		i bash/profile .bash_profile
		i bash/rc .bashrc
		i ssh/config .ssh/config
		i icons/ .local/share/icons/default
		[ "$PLATFORM" = 'android' ] && i termux/ .termux
		i inputrc .inputrc )

	sudo -v

	i() { set -- "$PWD/$1" "$i/$2"
		sudo mkdir -p "$(dirname "$2")"
		sudo cp -rT "$1" "$2"
		echo "'$1' > '$2'"; }

	( cd etc; i='/etc'
		i sudoers/ sudoers.d
		i pacman pacman.conf
		i ssh ssh/sshd_config
		i grub default/grub )
echo )

[ "$PLATFORM" = 'unknown' ] || . "run/$PLATFORM"

git init
