#!/usr/bin/env sh
set -e

. 'lib/sh/profile'

(
	cd etc

	i() {
		set -- "$PWD/$1" "$2"
		mkdir -p "$(dirname "$2")"
		ln -vsfT "$1" "$2"
	}

	(
		cd xdg
		for f in *; do
			i "$f" "$XDG_CONFIG_HOME/$f"
		done
	)

	(
		cd home

		i bash/profile ~/.bash_profile
		i bash/rc ~/.bashrc
		i inputrc ~/.inputrc
		i ssh/config ~/.ssh/config
		i icons/ ~/.local/share/icons/default
	)

	sudo -v || exit

	i() {
		sudo mkdir -p "$(dirname "$2")"
		sudo cp -vrT "$1" "$2"
	}

	(
		cd root

		i ssh /etc/ssh/sshd_config
		i sudoers/ /etc/sudoers.d
		i ly/ /etc/ly
		i grub/default /etc/default/grub
		i pacman /etc/pacman.conf
	)
) || true

[ "$PLATFORM" = 'unknown' ] || . "run/$PLATFORM"

git init
