#!/bin/python

from PIL import Image, ImageDraw
from random import random
import json
import math
import subprocess
import sys


fgc = "ffffff"
acc = "40e0d0"

a0 = math.pi * 2 * random()

mask = Image.open("i/mask.png")

outputs = json.JSONDecoder().decode(sys.stdin.read())


def run(file, output):
    return subprocess.run([
        "awww", "img", file,
        "--outputs", output["name"],
        "--transition-fps", f"{120}",
        "--transition-type", "center",
        "--transition-step", f"{64}",
        "--transition-bezier", f"{0.0},{0.0},{1.0},{1.0}"
    ])


def is_prime(n):
    i = 2
    while i * i <= n:
        if n % i == 0:
            return False
        i += 1
    return True


primes = [2]
for _ in range(2**15):
    o = primes[len(primes) - 1] + 1
    while not is_prime(o):
        o += 1
    primes += [o]


def is_masked(x, y):
    (x, y) = (x + mask.width / 2, y + mask.height / 2)
    if x >= 0 and y >= 0 and x < mask.width and y < mask.height:
        return not mask.getpixel((x, y))[3] == 0
    return True


for name in outputs:
    output = outputs[name]
    assert name == output["name"]

    w = output["logical"]["width"]
    h = output["logical"]["height"]
    d = math.sqrt((w / 2) ** 2 + (h / 2) ** 2)
    last = primes[len(primes) - 1]

    o = Image.new("RGBA", (w, h))
    draw = ImageDraw.Draw(o)

    for i in range(len(primes) - 1):
        n = primes[i]
        f = n * d / last
        (x, y) = (w / 2 + math.cos(a0 + n) * f, h / 2 + math.sin(a0 + n) * f)
        color = f"#{acc if primes[i + 1] - n == 2 else fgc}ff"
        if is_masked(x - w / 2, y - h / 2):
            draw.circle((x, y), 0.5, fill=color)

    file = f"o/{name}.png"
    o.save(file)
    run(file, output)
    print(name)
