#!/bin/sh
set -e && export SHELLOPTS
cd "$1"

{
	second=1
	minute=$((second * 60))
	hour=$((minute * 60))
	day=$((hour * 24))

	offset=$(python -c 'import time; print(-time.timezone)')

	read_hm(){( set -- $(cat); echo $((($1 * hour) + ($2 * minute))); )}
	write_hm(){( set -- $(cat); echo $(($1 / hour)) $(($1 % hour / minute)); )}

	i_date(){ command date --date "@$((epoch))" "$@"; }
}

while kill -0 "$PPID"; do
	i="$(
		set -e -- $EPOCHSECONDS
		{
			epoch=$1
			now=$(((epoch + offset) % day))
		}
		. ./run 2>&1
	)" || {
		notify-send \
			"timer/$(basename "$PWD")" \
			"$?: $i" \
			-t $((10 * 1000))
		sleep 10; }
done
