#!/bin/sh
i(){ xbacklight -get | sed 's/\..*//'; }
max(){ echo $(( $1 > $2 ? $1 : $2)); }
min(){ echo $(( $1 < $2 ? $1 : $2)); }

i=$(dmenu -p "brightness: $(i)/100" &)
[ -n "$i" ] || exit
s=$(min $(max $(($(max $(i) $i)-$(min $(i) $i))) 0) 100)

xbacklight -set "$i" -time $((s * 10)) -steps $s &
PID=$!
i="$(dunstify -p 'brightness' "$(i)")"
while kill -0 $PID; do
	dunstify -r "$i" 'brightness' "$(i)"
	sleep 0.01
done
dunstify -r "$i" 'brightness' "set to $(i)"
pkill systat-2
