#!/bin/sh
max(){ echo "$(($1>$2 ? $1 : $2 ))"; }
min(){ echo "$(($1<$2 ? $1 : $2 ))"; }
getbr(){ xbacklight -get | xbacklight -get | sed "s/\..*//"; }

BR1="$(getbr)"
MAX="$(cat "/sys/class/backlight/nvidia_0/max_brightness")"
BR="$(dmenu -p "brightness: $BR1/$MAX" &)"
STEPS="$(min "$(max "$(("$(max "$BR1" "$BR")" - "$(min "$BR1" "$BR")"))" 0)" 100)"

i="$(dunstify -p "brightness" "$(getbr)")"
xbacklight -set "$BR" -time "$(("$STEPS"*10))" -steps "$STEPS" &
PID=$!
while kill -0 $PID; do
	dunstify -r "$i" "brightness" "$(getbr)"
	sleep 0.01
done
dunstify -r "$i" "brightness" "set to $(getbr)"
pkill systat-2
