[options]
ParallelDownloads = 4
CleanMethod = KeepInstalled
Architecture = auto
CheckSpace
DisableDownloadTimeout

SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
RemoteFileSigLevel = Required

Color
ILoveCandy
VerbosePkgLists

[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[multilib]
Include = /etc/pacman.d/mirrorlist
