#!/bin/sh
cd $(mktemp -d)
python -m venv .venv
source .venv/bin/activate
python -m pip install --upgrade pip
python -m pip install tendo
python -m pip install pypresence
python "$DOTARCH/script/drpc/drpc.py" > /dev/null
